==19387== 8 bytes in 1 blocks are definitely lost in loss record 1 of 2
==19387==    at 0x4C31B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19387==    by 0x186787: receiver_create (receiver.c:107)
==19387==    by 0x18439B: create_test_receiver() (Tests.cpp:33)
==19387==    by 0x1843EE: Receiver_test_create_Test::TestBody() (Tests.cpp:43)
==19387==    by 0x1F048E: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2443)
==19387==    by 0x1E4146: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2479)
==19387==    by 0x19A8BF: testing::Test::Run() (gtest.cc:2517)
==19387==    by 0x19BDCD: testing::TestInfo::Run() (gtest.cc:2693)
==19387==    by 0x19CAA0: testing::TestCase::Run() (gtest.cc:2811)
==19387==    by 0x1B5B9A: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5177)
==19387==    by 0x1F255F: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2443)
==19387==    by 0x1E5EC7: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2479)
==19387==    by 0x1B2E59: testing::UnitTest::Run() (gtest.cc:4786)
==19387==    by 0x18619D: RUN_ALL_TESTS() (gtest.h:2341)
==19387==    by 0x186054: main (gtest_main.cc:36)
==19387== 
==19387== 8 bytes in 1 blocks are definitely lost in loss record 2 of 2
==19387==    at 0x4C31B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19387==    by 0x186787: receiver_create (receiver.c:107)
==19387==    by 0x18439B: create_test_receiver() (Tests.cpp:33)
==19387==    by 0x184AD7: Stream_test_stream_decode_Test::TestBody() (Tests.cpp:100)
==19387==    by 0x1F048E: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2443)
==19387==    by 0x1E4146: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2479)
==19387==    by 0x19A8BF: testing::Test::Run() (gtest.cc:2517)
==19387==    by 0x19BDCD: testing::TestInfo::Run() (gtest.cc:2693)
==19387==    by 0x19CAA0: testing::TestCase::Run() (gtest.cc:2811)
==19387==    by 0x1B5B9A: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5177)
==19387==    by 0x1F255F: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2443)
==19387==    by 0x1E5EC7: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2479)
==19387==    by 0x1B2E59: testing::UnitTest::Run() (gtest.cc:4786)
==19387==    by 0x18619D: RUN_ALL_TESTS() (gtest.h:2341)
==19387==    by 0x186054: main (gtest_main.cc:36)
==19387== 
